version: "3.8"

services:

  web:
    image: image-service
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DB_HOST: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PORT: 5432
      DEBUG: False
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: nginx-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
      - ./media:/media
    ports:
      - "80:80"
    depends_on:
      - web

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ../pgdata:/var/lib/postgresql/data
