# Generated by Django 4.2.5 on 2023-09-25 20:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagesservice.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('enable_original_link', models.BooleanField()),
                ('enable_generate_expiring_links', models.BooleanField()),
                ('is_builtin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('filename', models.ImageField(upload_to=imagesservice.utils.GenerateRandomFileName('images/originals/'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), imagesservice.utils.validate_image_min_height])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagesservice.accounttier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThumbnailSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(unique=True, verbose_name='height in px')),
                ('is_builtin', models.BooleanField(default=False)),
                ('tiers', models.ManyToManyField(blank=True, to='imagesservice.accounttier')),
            ],
        ),
        migrations.CreateModel(
            name='ThumbnailImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('height', models.IntegerField()),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('filename', models.ImageField(upload_to=imagesservice.utils.GenerateRandomFileName('images/thumb/'))),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_images', to='imagesservice.image')),
            ],
        ),
        migrations.CreateModel(
            name='ExpiringImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('expiration_datetime', models.DateTimeField()),
                ('expire_after', models.IntegerField(help_text='Expire after given number of seconds', validators=[django.core.validators.MinValueValidator(300, message='expire_after must be at least 300'), django.core.validators.MaxValueValidator(30000, message='expire_after cannot exceed 30000')])),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiring_images', to='imagesservice.image')),
            ],
        ),
    ]
